before_script:
  - echo "starting build UAM...."
  - echo $CI_COMMIT_TAG

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build_docker_image

build_docker_image-job:
  stage: build_docker_image
  image: wuyuw/dind
  script:
    - bash deploy/build.sh -t $CI_COMMIT_TAG -u $DOCKER_USER -p $DOCKER_PASSWORD
  only:
    - /(admin|api|rpc|job)-\d+\.\d+\.\d+$/
  tags:
    - mau_docker_runner
