name: build-docker-image
run-name: building
on:
  push:
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet
    tags:
      - 'admin-[1-9]+.[0-9]+.[0-9]+'
      - 'api-[1-9]+.[0-9]+.[0-9]+'
      - 'rpc-[1-9]+.[0-9]+.[0-9]+'
      - 'job-[1-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        # https://github.com/marketplace/actions/build-and-push-docker-images
        uses: docker/build-push-action@v4
        with:
          # build context dir
          context: .
          file: ./deploy/Dockerfile
          push: true
          # docker build arg
          build-args: |
            SERVICE=${{ service }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/uam-${{ service }}:${{ version }}
